baidunews:
    cl: 2
    rn: 50     #每页显示新闻条数
    pn: 0      #从0编号，表示rn个新闻中第一个的编号
    word: 'word'
    ie: 'utf-8'
baidunewssite:
    - news.163.com
    - news.sina.com.cn
    - news.ifeng.com
    - news.qq.com
    - news.sohu.com
    - news.xinhuanet.com
    - people.com.cn

baidunewsurl: 'http://www.baidu.com/s'
weibourl: 'https://m.weibo.cn/p/100103type=3&q= ' #https://m.weibo.cn/p/100103type=3&q=唐杰?type=user 
weibo:
    word: 'word'
zhihuuserurl: 'https://www.zhihu.com/search'
zhihuuser:
    type: 'people'
    q: 'word'
baidubaikeurl: 'http://baike.baidu.com/item/' #http://baike.baidu.com/item/唐杰?force=1
baidubaike:
    force: 1
newweibourl: 'http://s.weibo.com/user/&'
newweibo:
    nickname: 'weibo_user'