# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('baike', models.TextField(verbose_name='\u767e\u5ea6\u767e\u79d1')),
                ('weibo', models.TextField(verbose_name='\u65b0\u6d6a\u5fae\u535a')),
                ('zhihu', models.TextField(verbose_name='\u77e5\u4e4e')),
                ('news', models.TextField(verbose_name='\u65b0\u95fb')),
                ('picture', models.TextField(verbose_name='\u56fe\u7247')),
                ('keyword', models.TextField(verbose_name='\u5173\u952e\u5b57')),
                ('weight', models.FloatField()),
            ],
        ),
    ]
